# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14lTu5TKuIFNWTOEm-vsINaFnoBv5wT1x
"""

nombre = "Daniela Somadevilla";
edad = 26;
pyme = "La tiendita de dany";
activo = True;

print("Mi nombre es", nombre, "tengo ", edad, "años de edad y el nombre de mi emprendimiento es", pyme, "y su estado es", activo);